services:
    HeimrichHannot\ContaoDynamicFeedBundle\:
        resource: '../../{Controller}/*'
        autowire: true
        autoconfigure: true

    HeimrichHannot\ContaoDynamicFeedBundle\Component\NewsFeedGenerator:
        autowire: true

    hh.dynamicfeed.feed_generator:
        alias: HeimrichHannot\ContaoDynamicFeedBundle\Component\NewsFeedGenerator
        public: true

    hh.dynamicfeed.source.newsarchive:
        class: HeimrichHannot\ContaoDynamicFeedBundle\Components\NewsArchiveFeedSource
        tags: [hh.dynamicfeed.feed_source]